name: Build

on: [push]

env:
  GH_PAGES_DIR: gh-pages

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Publish generated content to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          # branch: pages # The branch the action should deploy to.
          # folder: ${{ env.GH_PAGES_DIR }} # The folder the action should deploy.
          dir: ${{ env.GH_PAGES_DIR }}
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
