name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

#      - name: Generate haddock content
#        run: stack build --haddock --haddock-arguments "--odir=haddock"

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: haddock
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
          email: zak.vitaly@yandex.ru.com
