name: Build

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Generate haddock content
        run: stack build --haddock --haddock-arguments "--odir=gh-pages/haddock"

      - name: Run Test
        run: stack test --coverage

      - name: Build Coverage
        run: stack hpc report labs

      - name: Copy Test Coverage to gh-pages
        run: cp -r $(stack path --local-hpc-root)/combined/custom gh-pages/hpc

      - name: Copy README.md to gh-pages
        run: cp README.md gh-pages/README.md

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: gh-pages
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
