name: Build

on:
  push:
    branches:
      - main

env:
  GH_PAGES_DIR: gh-pages

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Generate haddock content
        run: stack build --haddock --haddock-arguments "--odir=${{ env.GH_PAGES_DIR }}/haddock"

      - name: Run Test
        run: stack test --coverage

      - name: Build Coverage
        run: stack hpc report labs

      - name: Copy Test Coverage to ${{ env.GH_PAGES_DIR }}
        run: cp -r $(stack path --local-hpc-root)/combined/custom ${{ env.GH_PAGES_DIR }}/hpc

      - name: Copy README.md to ${{ env.GH_PAGES_DIR }}
        run: cp README.md ${{ env.GH_PAGES_DIR }}/README.md

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: ${{ env.GH_PAGES_DIR }}
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
